image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  PYTHONPATH: "."

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - test

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

test:
  stage: test
  script:
      - py.test -n 4 --cov=app
      - pylint app -f parseable>> pylint.log || true
  artifacts:
    paths:
    - results.html
    - results.xml
    - pylint.log
  